name: CI
on: [push, pull_request]
jobs:
  build-test:
    uses: cygporter/workflows/.github/workflows/build-test.yml@v2
    with:
      cygport_file: python-myst-parser.cygport
      bootstrap_packages: cygport python38-wheel python39-wheel
